version: '3.8'

services:
  python-execution-engine:
    build: .
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=False
      - MAX_EXECUTION_TIME=30
      - MAX_MEMORY_MB=512
      - BASE_DIR=/app/workspace
    volumes:
      - ./workspace:/app/workspace
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s